### ISSUE TITLE
TP-Link TL-WN722N support

### ISSUE THREAD

**Issue by engmas5** [vanhoefm/modwifi#12]
Hello Vanheof, 

I would like to thank you for the great work you presented here. I tried to run the experiments using TP-Link TL-WN722N  but it seems that TP-Link started producing this device using different chipset (Broadcom). Furthermore, I couldn't be able to find the TP-Link TL-WN722N  v1.0 that supports the ModWiFi driver. I used Netgear Wireless USB adapter WNA1100 (the older version) and it works fine. The problem is empowered since most of manufacturers doesn't announce the chipsets in the product technical details. You may consider indicating the exact version on the web page, since manufacturers sometimes change the chipsets in the newer versions. 

Best regards,
Mohammad

**Comment by vanhoefm** [comment]
Thank you for this warning. WikiDevi confirms that the [newer TL-WN722N v2](https://wikidevi.com/wiki/TP-LINK_TL-WN722N_v2) no longer uses an Atheros chipset, but instead uses a Realtek chip.

It's a shame in my opinion, this dongle was a good cheap option to monitor the 2.4 GHz band.
