### ISSUE TITLE
compat: module verification failed

### ISSUE THREAD

**Issue by Qin-Long** [vanhoefm/modwifi#15]
It doesn't work at all after i compile these code. I got some message when i make install the modules:
"SSL error:2006D080:BIO routines:BIO_new_file:no such file: bss_file.c:178
sign-file: certs/signing_key.pem: No such file or directory”
And I got the message 
"[  177.032667] compat: module verification failed: signature and/or required key missing - tainting kernel
[  177.033199] Loading modules backported from Linux version v4.4-18-gd7fd3d9
[  177.033201] Backport generated by backports.git v4.4.2-1-5-g6b791b0
"
when I use "dmesg"
Could you please tell me how to fix it ,Thank you for your time.

**Comment by vanhoefm** [comment]
In case someone is still reading this: even with this warning message, everything should still be working.
