### ISSUE TITLE
How to confirm if the continuous jammer is working?

### ISSUE THREAD

**Issue by 2tjc3yg** [vanhoefm/modwifi#16]
Hi. Many thanks for the work done.
I try to work with Xubuntu-Modwifi (official image) and continuous Jamming seems not work ... (tested with [spectral scan tool](https://github.com/LorenzoBianconi/ath_spectral) )
Can I acquire attack samples with spectral analysis feature of AR9271 chipset?

What equipment do I use:
1. TLWN722N v.1 + Xubuntu-Modwifi (official image)
2. TLWN722N v.1 + Xubuntu-Modwifi (official image) + modwifi-4.4-1.tar.gz (installed in the official manual, the drivers (fw) are replaced!)
3. TLWN722N v.1 + Xubuntu-Modwifi (official image) + modwifi-4.7.4-experimental-1.tar.gz (installed in the official manual, the drivers (fw) are replaced!)

**Comment by brunoaduarte** [comment]
@2tjc3yg, you could have saved a lot of your time if you had read the instructions first ... the "continuous jammer" code does nothing on the public release, they have removed it.

**Comment by vanhoefm** [comment]
For anyone reading this: access to the continuous jammer can be requested for research purposes (send me an email).
