### ISSUE TITLE
Reactive jam does not work

### ISSUE THREAD

**Issue by brunoaduarte** [vanhoefm/modwifi#19]
I tried the "reactivejam" tool here targetting my home AP but it seems not to work. It does not drop the connection to the AP and beacons still arrive on the receiver.

**Comment by vanhoefm** [comment]
For anyone still reading this: the reliability depends on how close the targeted device is to the AP. I recommend to move the targeted device far away from the AP, and put the jammer in the middle of the AP and the targeted device.
