### ISSUE TITLE
Stop chip from dropping with erroneous FCS in ad-hoc mode

### ISSUE THREAD

**Issue by WirelessWizard** [vanhoefm/modwifi#24]
how can I force the chip to accept all incoming packets, including packets with an incorrect FCS & pass it up the stack as if it had a correct FCS?

I know that you suggested using `sudo iw wlan1 set monitor fcsfail` which does not allow me to see the data packets. I only see probes and beacons.

I am operating in an wpa2 ad-hoc/mesh network and using your modwifi-5.3-rc4-1.tar.gz release.

**Comment by vanhoefm** [comment]
You can try adding a second virtual interface in monitor mode:

```
sudo iw wlan1 interface add wlan1mon type monitor
sudo iw wlan1mon set monitor fcsfail
```

Using an ad-hoc/mesh interface alone won't let you see all traffic. I'm not sure if you can combine a virtual monitor interface with ad-hoc/mesh mode, but you can try.

**Comment by WirelessWizard** [comment]
Thank you very much! I never tried that before.
