### ISSUE TITLE
Exposing additional registers

### ISSUE THREAD

**Issue by WirelessWizard** [vanhoefm/modwifi#26]
I'm trying to expose the AR9271 `PHY Error Mask (MAC_PCU_PHY_ERROR_MASK)` register, specifically bit 26, in an attempt to stop the `CCK CRC header error` from dropping frames with an invalid FCS.
How can I control this register via debugfs? Is it just a matter of following the structure in your commit to [htc_drv_debug.c](https://github.com/torvalds/linux/commit/8afeb9d41d625b0c62551a38e898f95c14d5d748)?
If not, how else can I force the "crc_error" flag of "Rx Status Descriptor" (Word 12, Bit 2) to always have a value of zero?

Also, when you have a chance... I'd appreciate talking to you about your private code via email

**Comment by WirelessWizard** [comment]
Side note: I made a patch file based off of your driver modifications from the "modwifi-linux" repo.
I tested it on kernel 5.3.15. 
[modwifi.txt](https://github.com/vanhoefm/modwifi/files/4671106/modwifi.txt)

**Comment by rodrigowue** [comment]
Hey @WirelessWizard ,

Do you have any updates on this? I'm also trying to expose some registers to the userspace.


Best,
Rodrigo

**Comment by WirelessWizard** [comment]
Take a look at https://github.com/vanhoefm/modwifi-ath9k-htc, you would want to modify the debugfs and add an entry that controls the desired register.
It's been a while so I forget exactly where I needed to go to do that.

**Comment by WirelessWizard** [comment]
Take a look at this: https://github.com/vanhoefm/modwifi-ath9k-htc/blob/research/docs/firmware_commands.md

**Comment by rodrigowue** [comment]
Thank you very much, @WirelessWizard !!

This definitely helps me :)
