### ISSUE TITLE
how to set txpower

### ISSUE THREAD

**Issue by jackieshih** [vanhoefm/modwifi#3]
Hi, I'm researching how to create power adaptive over the AR9271 with raspberry pi 2,I want to change txpower in monitor mode, But when I use "iw dev wlan0 set txpower fixed 500".It looks like no problem.But the txpower won't change, it's still 20 dBm Now,I have the source firmware source,can you give me some suggestion?

**Comment by vanhoefm** [comment]
You can try to look and experiment with the MAC_PCU_TPC register: "This register set the transmit power for selfgenerated response frames." See https://github.com/vanhoefm/modwifi-ath9k-htc/blob/research/docs/AR9271.pdf and https://github.com/vanhoefm/modwifi-ath9k-htc/blob/research/docs/AR9280.pdf

Try grepping through the firmware code on words like "power", "tpc", "pwr", etc. Maybe you can find something usefull.

**Comment by wice222** [comment]
git clone git://github.com/matplotlib/matplotlib.git
cd matplotlib
python setup.py install
apt-get build-dep python-matplotlib
python setup.py develop
git pull

apt-get install python-matplotlib pkg-config cdbs debhelper gcc wireless-regdb libgcrypt11-dev libnl1 openssl python-m2crypto libgcrypt11-dev libgcrypt11-dev libnl-dev


cat <<EOF>> /etc/apt/sources.list
deb http://ftp.de.debian.org/debian wheezy main 
EOF
apt-get update
apt-get install libnl-dev

cd wireless-regdb

# Downloading packages
wget https://www.kernel.org/pub/software/network/crda/crda-1.1.3.tar.xz
wget http://linuxwireless.org/download/wireless-regdb/debs/wireless-regdb_2009.11.25.orig.tar.bz2
tar xvjf wireless-regdb_2009.11.25.orig.tar.bz2
cd wireless-regdb-2009.11.25
openssl genrsa -out your.key.priv.pem 2048
openssl rsa -in your.key.priv.pem -out your.key.pub.pem -pubout -outform PEM

nano /rpms/wireless-regdb-2009.11.25/db2bin.py
# Replacing 
#!/usr/bin/env python
# with 
#!/usr/bin/python2
# editing rules , changing 20's to 30-40's per our region
nano db.txt
make
# moving new file
mv /lib/crda/regulatory.bin /lib/crda/regulatoryOLD.bin
cp /rpms/wireless-regdb-2009.11.25/regulatory.bin /lib/crda/regulatory.bin
mkdir /usr/lib/crda
mv /usr/lib/crda/regulatory.bin /usr/lib/crda/regulatoryOLD.bin
cp /rpms/wireless-regdb-2009.11.25/regulatory.bin /usr/lib/crda/regulatory.bin
cd /rpms
tar xf crda-1.1.3.tar.xz
cd crda-1.1.3
cp -v /rpms/wireless-regdb-2009.11.25/*.key.pub.pem /rpms/crda-1.1.3/pubkeys/
cp -v /rpms/wireless-regdb-2009.11.25/linville.key.pub.pem /rpms/crda-1.1.3/pubkeys/linville.key.pub.pem
cp -v /rpms/wireless-regdb-2009.11.25/root.key.pub.pem /rpms/crda-1.1.3/pubkeys/root.key.pub.pem
make
make install
mkdir /usr/lib/crda/pubkeys
mv /usr/lib/crda/pubkeys /usr/lib/crda/Back_pubkeys
cp -avr /rpms/crda-1.1.3/pubkeys/ /usr/lib/crda/pubkeys

apt-get -y update && apt-get -y upgrade

you'll need to change Directories ;)
