### ISSUE TITLE
Tools won't compile due to the lack of Makefile

### ISSUE THREAD

**Issue by ieguiguren** [vanhoefm/modwifi#5]
Both, Debian stretch and Ubuntu trusty, won't compile tools due to the lack of the Makefile file. Thus, this fails:

> cd tools && make all

`[~/dev/modwifi]>cd tools/
[~/dev/modwifi/tools]>make all
make: *** No rule to make target `all'.  Stop.
[~/dev/modwifi/tools]>ls
CMakeFiles	MacAddr.cpp	 SeqnumStats.h	 channelmitm.cpp  constantjam.cpp  crypto.h   fastreply.cpp	 osal_nl.cpp  pcap.cpp	       util.cpp
CMakeLists.txt	MacAddr.h	 SeqnumType.cpp  chopstate.cpp	  crc.cpp	   eapol.cpp  ieee80211header.h  osal_nl.h    pcap.h	       util.h
ClientInfo.cpp	SeqnumInfo.h	 SeqnumType.h	 chopstate.h	  crc.h		   eapol.h    libutil.a		 osal_wi.cpp  reactivejam
ClientInfo.h	SeqnumStats.cpp  channelmitm	 constantjam	  crypto.cpp	   fastreply  nl80211.h		 osal_wi.h    reactivejam.cpp
`

**Comment by vanhoefm** [comment]
Try running:

`cd tools`
`cmake CMakeLists.txt`
`make`

**Comment by ieguiguren** [comment]
Had to install cmake previously but this worked it out.  I've updated the doc in the pull request. Thank you.
