### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by brainteasers007** [vanhoefm/modwifi#7]
Hey, guys.

I get an error when I do a make in drivers folder.

root@kali: /modwifi/drivers# make
  CC [M]  /root/modwifi/drivers/net/wireless/nl80211.o
/root/modwifi/drivers/net/wireless/nl80211.c: In function ‘nl80211_send_iface’:
**/root/modwifi/drivers/net/wireless/nl80211.c:2405:6: error: implicit declaration of function ‘nla_put_u64’ [-Werror=implicit-function-declaration]
      nla_put_u64(msg, NL80211_ATTR_WDEV, wdev_id(wdev)) ||
      ^**
cc1: some warnings being treated as errors
/usr/src/linux-headers-4.8.0-kali1-common/scripts/Makefile.build:294: recipe for target '/root/modwifi/drivers/net/wireless/nl80211.o' failed
make[8]: *** [/root/modwifi/drivers/net/wireless/nl80211.o] Error 1
/usr/src/linux-headers-4.8.0-kali1-common/scripts/Makefile.build:445: recipe for target '/root/modwifi/drivers/net/wireless' failed
make[7]: *** [/root/modwifi/drivers/net/wireless] Error 2
/usr/src/linux-headers-4.8.0-kali1-common/Makefile:1488: recipe for target '_module_/root/modwifi/drivers' failed
make[6]: *** [_module_/root/modwifi/drivers] Error 2
Makefile:150: recipe for target 'sub-make' failed
make[5]: *** [sub-make] Error 2
Makefile:8: recipe for target 'all' failed
make[4]: *** [all] Error 2
Makefile.build:6: recipe for target 'modules' failed
make[3]: *** [modules] Error 2
Makefile.real:88: recipe for target 'modules' failed
make[2]: *** [modules] Error 2
Makefile:40: recipe for target 'modules' failed
make[1]: *** [modules] Error 2
Makefile:30: recipe for target 'default' failed
make: *** [default] Error 2
root@kali:~/modwifi/drivers#

**Comment by vanhoefm** [comment]
What's your kernel version? Check using `uname -a`. Version 3.0 up to and including 4.4 is supported. There is also an experimental release for kernel 4.7.

**Comment by brainteasers007** [comment]
Thanks For The Reply
I guess that's the problem.

**root@kali:# uname -a
Linux kali 4.8.0-kali1-amd64 #1 SMP Debian 4.8.5-1kali1 (2016-11-04) x86_64 GNU/Linux**

I was looking for a solution for my Wireless dongle (TP-LINK TL-WN722N - ath9k_htc). Kali detects my Atheros card (lsusb), but there are no wireless interfaces (ifconfig, iwconfig).

I searched the logs and found an error in logs stating that the ath9k driver failed to download and USB layer deinitialized.

usb 1-1: ath9k_htc: Firmware htc_9271.fw requested
usbcore: registered new interface driver ath9k_htc
usb 1-1: ath9k_htc: Firmware - htc_9271.fw download failed
usb 1-1: ath9k_htc: USB layer deinitialized

Is there any other custom firmware that could resolve the problem?

**Comment by vanhoefm** [comment]
Are you trying to get the device working using the default settings, drivers, and firmware? We do not provide support for that, knowing how all distributions works is simply infeasible. For kali you probably have to install something like the `firmware-atheros` package or similar.
