### ISSUE TITLE
Apply this work to Ath9k driver?

### ISSUE THREAD

**Issue by Riconaute** [vanhoefm/modwifi#8]
Hello,

You think it's possible to apply modwifi on ath9k_htc driver to ath9k driver please ?
If yes, how to do that please?

Because I have a device which works with Ath9k drivers.

Thanks,

Regards,

Eric

**Comment by vanhoefm** [comment]
It's not possible to directly apply the patches to ath9k. I think very similar patches can be made, but this will require quite some work. Your best option is to buy an ath9k_htc device.

**Comment by Riconaute** [comment]
ok thanks
