### ISSUE TITLE
FCS fails to Ath9k?

### ISSUE THREAD

**Issue by Riconaute** [vanhoefm/modwifi#9]
Hello,

Sorry to disturb you again. Is it complicated to integrated only the FCS FAIL functionality on ath9k? 
Which file should be modify please ?

Thanks,

Regards,

Eric

**Comment by vanhoefm** [comment]
I don't understand your question. Commands like `sudo iw wlan1 set monitor fcsfail` are general commands that are already supported by default in Linux.
